name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - staging  
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.STAGING_APP_PUBLISH_PROFILE }}  
  WEBAPP_NAME: ${{ secrets.STAGING_WEBAPP_NAME }}
  SKBT_BRANCH: ${{ secrets.STAGING_SKBT_BRANCH }}
  SKBT_HTTP_HOST: ${{ secrets.STAGING_SKBT_HTTP_HOST }}
  SKBT_SUBFOLDER: ${{ secrets.STAGING_SKBT_SUBFOLDER }}
  SKBT_BASEPATH: ${{ secrets.STAGING_SKBT_BASEPATH }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          envsubst '\$SKBT_BRANCH,\$SKBT_HTTP_HOST,\$SKBT_SUBFOLDER,\$SKBT_BASEPATH' < .env.template > .env
          cat .env 
          npm install
          npm run build
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: ./build/standalone
